# Generated by Django 5.0.1 on 2024-02-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father',
            field=models.TextField(max_length=50),
        ),
    ]
