# Generated by Django 5.0.1 on 2024-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
